image: node:18

stages:
  - build
  - deploy

# Cache node_modules to speed up subsequent runs
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - packages/docs/node_modules/
  policy: pull-push

# Build the VitePress documentation
build_docs:
  stage: build
  script:
    - npm ci
    - cd packages/docs
    - npm run docs:build
  artifacts:
    paths:
      - packages/docs/.vitepress/dist
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Deploy to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - build_docs
  script:
    - mkdir -p public
    - cp -r packages/docs/.vitepress/dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 