name: Release
on:
  push:
    branches:
      - main
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Build docs
        run: npm run docs
      - name: Zip frontend
        run: cd packages/frontend/dist && zip -r ../../../frontend.zip .
      - name: Zip documentation
        run: cd packages/docs/docs/.vitepress/dist && zip -r ../../../../../docs.zip .
      - name: Create services package
        run: |
          mkdir -p release
          cp docker-compose.yml release/
          cp env.tempalte release/env.template
          cp -r packages/api-gateway/dist release/api-gateway
          cp -r packages/auth-service/dist release/auth-service
          cp -r packages/user-service/dist release/user-service
          cp -r packages/lobby-service/dist release/lobby-service
          cp -r packages/auction-service/dist release/auction-service
          cp -r packages/common/dist release/common
          cd release && zip -r ../auction-services.zip .
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release 