name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build

      - name: Build docs
        run: npm run docs:build -w @auction/docs

      - name: Package frontend
        run: |
          cd packages/frontend/dist
          zip -r ../../../frontend.zip .

      - name: Package docs
        run: |
          cd packages/docs/docs/.vitepress/dist
          zip -r ../../../../docs.zip .

      - name: Package backend services
        run: |
          cd packages
          zip -r ../auction-services.zip \
            auction-service/dist \
            user-service/dist \
            auth-service/dist \
            api-gateway/dist \
            lobby-service/dist \
            common/dist

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release 